version: '3.8'

services:
  # メイン開発環境
  dev-environment:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: serena-autonomous-dev:latest
    container_name: serena-dev
    hostname: serena-dev
    
    # GPU設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # ボリューム設定
    volumes:
      # プロジェクトファイル
      - .:/workspaces:cached
      # Serena永続化
      - serena-data:/root/.serena
      # Gemini設定
      - gemini-config:/root/.gemini
      # Claude設定
      - claude-config:/root/.claude
      # PDFライブラリ（存在する場合）
      - ${HOME}/PDF:/root/PDF:ro
      # Docker in Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH設定（存在する場合）
      - ${HOME}/.ssh:/root/.ssh:ro
      # キャッシュ
      - npm-cache:/root/.npm
      - pip-cache:/root/.cache/pip
      - uv-cache:/root/.cache/uv
    
    # 環境変数
    environment:
      # GPU設定
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=all
      # Serena設定
      - SERENA_AUTO_LEVEL=5
      - SERENA_CONTEXT=ide-assistant
      - SERENA_PROJECT_PATH=/workspaces
      # API Keys (from host environment)
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # 開発設定
      - NODE_ENV=development
      - PYTHONPATH=/workspaces
      # パス設定（uvx用）
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
    
    # ネットワーク設定
    network_mode: host
    
    # セキュリティ設定
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    
    # リソース制限
    mem_limit: 32g
    memswap_limit: 32g
    shm_size: 16g
    
    # 起動設定
    stdin_open: true
    tty: true
    restart: unless-stopped
    
    # 起動時のコマンド（ツールのインストールを確実に実行）
    command: |
      bash -c "
        echo '=== Installing Serena dependencies ===' &&
        if ! pyenv versions --bare | grep -q '^3.11.9$'; then
          echo 'Installing Python 3.11.9...' &&
          pyenv install 3.11.9
        fi &&
        if ! $HOME/.pyenv/versions/3.11.9/bin/pip list | grep -q 'serena-agent'; then
          echo 'Installing Serena Agent...' &&
          $HOME/.pyenv/versions/3.11.9/bin/pip install git+https://github.com/oraios/serena
        fi &&
        if [ ! -L /usr/local/bin/serena ]; then
          echo 'Creating symlink for serena...' &&
          ln -s $HOME/.pyenv/versions/3.11.9/bin/serena /usr/local/bin/serena
        fi &&
        echo '=== Installing missing tools ===' &&
        if ! command -v claude &> /dev/null; then
          echo 'Installing Claude Code...' &&
          npm install -g @anthropic-ai/claude-code
        fi &&
        if ! command -v gemini &> /dev/null; then
          echo 'Installing Gemini CLI...' &&
          npm install -g @google/gemini-cli
        fi &&
        echo '=== Starting services ===' &&
        exec /entrypoint.sh /bin/bash
      "
    
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9121/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  # Serena-MCP専用サーバー（代替オプション）
  serena-mcp:
    image: ghcr.io/oraios/serena:latest
    container_name: serena-mcp-server
    hostname: serena-mcp
    profiles: ["standalone-serena"]  # デフォルトでは起動しない
    
    volumes:
      - .:/workspaces/project:cached
      - serena-data:/root/.serena
    
    environment:
      - SERENA_AUTO_LEVEL=5
      - SERENA_CONTEXT=ide-assistant
    
    ports:
      - "9121:9121"     # SSE Server
      - "24282:24282"   # Dashboard
    
    command: >
      serena start-mcp-server
      --transport sse
      --port 9121
      --context ide-assistant
      --auto-level 5
      --project /workspaces/project
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9121/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Jupyter Lab（オプション）
  jupyter:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: jupyter-lab
    profiles: ["jupyter"]  # 明示的に指定した場合のみ起動
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    volumes:
      - .:/workspaces:cached
      - jupyter-data:/root/.jupyter
    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-serena2024}
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
    
    ports:
      - "8888:8888"
    
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=${JUPYTER_TOKEN:-serena2024}
    
    restart: unless-stopped

# ボリューム定義
volumes:
  serena-data:
    driver: local
  gemini-config:
    driver: local
  claude-config:
    driver: local
  npm-cache:
    driver: local
  pip-cache:
    driver: local
  uv-cache:
    driver: local
  jupyter-data:
    driver: local

# ネットワーク定義
networks:
  default:
    name: serena-network
    driver: bridge